import Head from "next/head";
import styles from "../styles/GetServerSideProps.module.scss";
import List from "../components/PostList";
import { request } from "../utils/request";

const GetServerSideProps = (props) => {
  const { data } = props || { data: [] };

  return (
    <div className={styles.container}>
      <Head>
        <title>8 next official web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <List data={data} />
    </div>
  );
};

// SSG 静态生成
export const getStaticProps = async (context) => {
  console.log("context", context);

  const data = await request("http://localhost:3000/api/postList");
  return { props: { data } };
};

export default GetServerSideProps;
