import Head from "next/head";
import styles from "../styles/GetServerSideProps.module.scss";
import List from "../components/PostList";
import { request } from "../utils/request";

const GetServerSideProps = (props) => {
  const { data } = props || { data: [] };
  console.log(
    "浏览器环境访问: node环境中的环境变量，因为process.env只有node环境中存在 => process.env.HOST => ",
    process.env.HOST
  );

  console.log(
    "浏览器环境访问: process.env.NEXT_PUBLIC_FOR_ALL => ",
    process.env.NEXT_PUBLIC_FOR_ALL
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>8 next official web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <List data={data} />
    </div>
  );
};

// SSG 静态生成
export const getStaticProps = async (context) => {
  console.log("context", context);

  console.log(
    "node环境访问: node环境中的环境变量，因为process.env只有node环境中存在 => process.env.HOST => ",
    process.env.HOST
  );

  console.log(
    "node环境访问: process.env.NEXT_PUBLIC_FOR_ALL",
    process.env.NEXT_PUBLIC_FOR_ALL
  );

  const data = await request("http://localhost:3000/api/postList");
  return { props: { data } };
};

export default GetServerSideProps;
