import Head from "next/head";
import Card from "../components/Card";
import styles from "../styles/WebHome.module.scss";

export default function WebHome() {
  return (
    <div className={styles.container}>
      <Head>
        <title>8 next official web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Card></Card>
      </main>
    </div>
  );
}
